#!/bin/bash
#SBATCH --job-name=<JOB_NAME>
#SBATCH --account=fc_tardigrade
#SBATCH --partition=savio2
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=<NUM_CORES>
#SBATCH --cpus-per-task=1
#SBATCH --time=<WALL_CLOCK_LIMIT>
<COMMAND_TO_RUN>